# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: code-with-quarkus-example
  namespace: devhub-demo
  description: Simple Quarkus Sample
  annotations:
    backstage.io/source-location: url:https://github.com/geoffallendev/code-with-quarkus
    github.com/project-slug: geoffallendev/code-with-quarkus
    quay.io/repository-slug: "/geoallen/quarkus"

spec:
  type: service
  lifecycle: experimental
  owner: "geoffallendev"
  providesApis:
    - "code-with-quarkus"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "code-with-quarkus"
  description: "A cool quarkus app"
spec:
  type: openapi
  lifecycle: production
  owner: "geoffallendev"
  definition:
    $text: ./openapi.yaml
